Python-Web-Basics-Softuni/ExamPrep/ExamPrep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses_tracker.urls')),
]

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/urls.py
from django.urls import path

from expenses_tracker.views.expenses import create_expense, edit_expense, delete_expense
from expenses_tracker.views.index import index
from expenses_tracker.views.profiles import delete_profile, edit_profile, profile_index, create_profile

urlpatterns = (
    # Index
    path('', index, name='index'),

    # Expenses
    path('create/', create_expense, name='create expense'),
    path('edit/<int:pk>/', edit_expense, name='edit expense'),
    path('delete/<int:pk>/', delete_expense, name='delete expense'),

    # Profiles
    path('profile/', profile_index, name='profile index'),
    path('profile/create/', create_profile, name='create profile'),
    path('profile/edit/', edit_profile, name='edit profile'),
    path('profile/delete/', delete_profile, name='delete profile'),
)

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/models.py
from django.db import models


# Create your models here.
class Profile(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    budget = models.IntegerField()


class Expense(models.Model):
    title = models.CharField(max_length=50)
    image_url = models.URLField()
    description = models.TextField()
    price = models.FloatField()

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/forms/expense.py
from django import forms

from expenses_tracker.models import Expense


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'
        labels = {
            'image_url': "Link to Image",
        }

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/forms/profiles.py
from django import forms

from expenses_tracker.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/views/expenses.py
from django.shortcuts import render, redirect

from expenses_tracker.forms.expense import ExpenseForm
from expenses_tracker.models import Expense


def create_expense(request):
    if request.method == "GET":
        context = {
            'form': ExpenseForm(),
        }
        return render(request, 'expense-create.html', context)
    else:
        form = ExpenseForm(request.POST)

        if form.is_valid():
            expense = Expense(title=form.cleaned_data["title"],
                              description=form.cleaned_data["description"],
                              image_url=form.cleaned_data["image_url"],
                              price=form.cleaned_data["price"])
            expense.save()
            return redirect('index')
        context = {
            'form': ExpenseForm(),
        }
        return render(request, 'expense-create.html', context)


def edit_expense(request, pk):
    expense = Expense.objects.get(pk=pk)

    if request.method == "GET":
        context = {
            'form': ExpenseForm(instance=expense),
        }
        return render(request, 'expense-edit.html', context)
    else:
        form = ExpenseForm(request.POST)

        if form.is_valid():
            expense.title = form.cleaned_data["title"]
            expense.description = form.cleaned_data["description"]
            expense.image_url = form.cleaned_data["image_url"]
            expense.price = form.cleaned_data["price"]
            expense.save()
            return redirect('index')
        context = {
            'form': ExpenseForm(instance=expense),
        }
        return render(request, 'expense-edit.html', context)


def delete_expense(request, pk):
    expense = Expense.objects.get(pk=pk)

    if request.method == "GET":
        form = ExpenseForm(instance=expense)
        form.fields['title'].widget.attrs['disabled'] = True
        form.fields['description'].widget.attrs['disabled'] = True
        form.fields['image_url'].widget.attrs['disabled'] = True
        form.fields['price'].widget.attrs['disabled'] = True
        context = {
            'form': form,
        }
        return render(request, 'expense-delete.html', context)
    else:
        expense.delete()
        return redirect('index')

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/views/index.py
from django.shortcuts import render

from expenses_tracker.models import Profile, Expense
from expenses_tracker.views.profiles import create_profile


def money_left():
    profile_budget = Profile.objects.all()[0].budget
    for expense in Expense.objects.all():
        profile_budget -= expense.price

    return profile_budget

def index(request):
    if Profile.objects.exists():
        context = {
            'profile': Profile.objects.all()[0],
            'expenses': Expense.objects.all(),
            'money_left': money_left(),
        }
        return render(request, 'home-with-profile.html', context)
    else:
        return create_profile(request)

Python-Web-Basics-Softuni/ExamPrep/expenses_tracker/views/profiles.py
from django.shortcuts import redirect, render

from expenses_tracker.forms.profiles import ProfileForm
from expenses_tracker.models import Profile, Expense


def profile_index(request):
    context = {
        "profile": Profile.objects.all()[0]
    }
    return render(request, "profile.html", context)


def edit_profile(request):
    profile = Profile.objects.all()[0]
    if request.method == "GET":
        context = {
            "form": ProfileForm(instance=profile)
        }
        return render(request, "profile-edit.html", context)
    else:
        form = ProfileForm(request.POST)

        if form.is_valid():
            profile.budget = form.cleaned_data["budget"]
            profile.first_name = form.cleaned_data["first_name"]
            profile.last_name = form.cleaned_data["last_name"]

            profile.save()
            return redirect("profile index")
        context = {
            "form": ProfileForm(instance=profile)
        }
        return render(request, "profile-edit.html", context)


def delete_profile(request):
    profile = Profile.objects.all()[0]

    if request.method == "GET":
        form = ProfileForm(instance=profile)
        form.fields["budget"].widget.attrs["disable"] = True
        form.fields["first_name"].widget.attrs["disable"] = True
        form.fields["last_name"].widget.attrs["disable"] = True
        context = {
            "form": form,
        }
        return render(request, "profile-delete.html", context)
    else:
        expenses = Expense.objects.all()
        expenses.delete()
        profile.delete()

        return redirect('index')


def create_profile(request):
    if request.method == "GET":
        context = {
            'form': ProfileForm(),
        }
        return render(request, 'home-no-profile.html', context)
    else:
        form = ProfileForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('index')
        context = {
            'form': form,
        }
        return render(request, 'home-no-profile.html', context)

Python-Web-Basics-Softuni/ExamPrep/templates/expense-create.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="../static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Create Expense</h1>
<div class="form">
    <form method="POST" action="{% url 'create expense' %}">
        {{ form.title.label }}
        {{ form.title }}

        {{ form.description.label }}
        {{ form.description }}

        {{ form.image_url.label }}
        {{ form.image_url }}

        {{ form.price.label }}
        {{ form.price }}

        {% csrf_token %}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw">#}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" maxlength="50" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#        <label for="imageUrl">Link to Image</label>#}
{#        <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" step="any" required="" id="id_price">#}

        <input type="submit" value="Create">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/expense-delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="/static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Delete Expense</h1>
<div class="form">
    <form method="POST">
        {{ form.title.label }}
        {{ form.title }}

        {{ form.description.label }}
        {{ form.description }}

        {{ form.image_url.label }}
        {{ form.image_url }}

        {{ form.price.label }}
        {{ form.price }}

        {% csrf_token %}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc"> #}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" disabled="" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
{##}
{#        <label for="image_url">Link to Image</label>#}
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" disabled="" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" value="1000.0" step="any" disabled="" required="" id="id_price">#}

        <input type="submit" value="Delete">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/expense-edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="/static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Edit Expense</h1>
<div class="form">
    <form method="POST">
        {{ form.title.label }}
        {{ form.title }}

        {{ form.description.label }}
        {{ form.description }}

        {{ form.image_url.label }}
        {{ form.image_url }}

        {{ form.price.label }}
        {{ form.price }}

        {% csrf_token %}
        <input type="submit" value="Edit">
{#        <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS">#}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
{##}
{#        <label for="image_url">Link to Image</label>#}
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" value="1000.0" step="any" required="" id="id_price">#}
{##}
{##}
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/home-no-profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="/static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your data</h1>
<div class="form">
    <form method="POST" action="{% url 'create profile' %}">
        {{ form.budget.label }}
        {{ form.budget }}

        {{ form.first_name.label }}
        {{ form.first_name }}

        {{ form.last_name.label }}
        {{ form.last_name }}

        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/home-with-profile.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="../static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
<div class="body">


    {% if expenses %}
        <div>
            <h1>Summary</h1>
            <h1>
                <ul class="expenses-list">
                    <li class="blue">{{ profile.budget }}$</li>
                    {% for expense in expenses %}
                        <li class="red"> - {{ expense.price }}$</li>
                    {% endfor %}

                    <li class="green">= {{ money_left }}$ left</li>
                </ul>
            </h1>
        </div>
    {% endif %}

    <h1>My Expenses</h1>
    <button><a href="/create">Add Expense</a></button>
    {% if expenses %}
        <div class="expenses-container">
            {% for expense in expenses %}
                <div class="expense-container">
                    <h2>{{ expense.title }}</h2>
                    <hr>
                    <img src="{{ expense.image_url }}">
                    <p>{{ expense.description }}</p>
                    <div class="expense-detail">
                        <div>
                            <p>Price: {{ expense.price }}$</p>
                        </div>
                        <div class="right">
                            <button class="edit"><a href="{% url 'edit expense' expense.id %}">Edit</a></button>
                            <button class="delete"><a href="{% url 'delete expense' expense.id %}">Delete</a></button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

</div>
<footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body>
</html>

Python-Web-Basics-Softuni/ExamPrep/templates/profile-delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="/static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Are you sure you want to delete your profile?</h1>
<form method="POST">
{% csrf_token %}
<button class="delete">Confirm</button>
</form>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/profile-edit.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="/static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your new data</h1>
<div class="form">
    <form method="POST">
        {% csrf_token %}

        {{ form.budget.label }}
        {{ form.budget }}

        {{ form.first_name.label }}
        {{ form.first_name }}

        {{ form.last_name.label }}
        {{ form.last_name }}

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Python-Web-Basics-Softuni/ExamPrep/templates/profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="../static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Your Profile</h1>
<div class="expenses-container">
    <div class="expense-container">
        <h2>{{ profile.first_name }} {{ profile.last_name }}</h2>
        <hr>
        <img src="../static/images/user.png">
        <p>In your profile you can edit your profile data</p>
        <div class="expense-detail">
            <div>
                <p>Budget Left: {{ profile.budget }}$</p>
            </div>
            <div class="right">
                <button class="edit"><a href="{% url 'edit profile' %}">Edit Profile</a></button>
                <button class="delete"><a href="{% url 'delete profile' %}">Delete Profile</a></button>
            </div>
        </div>
    </div>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>